# Generated by Django 2.1.7 on 2019-03-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0002_auto_20190328_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MARTICLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('ctime', models.DateField(auto_now_add=True)),
                ('audit', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_writer', to='pblog.MUSER')),
            ],
            options={
                'verbose_name_plural': 'MARTICLEs',
                'verbose_name': 'MARTICLE',
            },
        ),
    ]
