# Generated by Django 2.1.7 on 2019-03-29 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pblog', '0008_auto_20190328_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='MALBUM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('ctime', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MALBUMs',
                'verbose_name': 'MALBUM',
            },
        ),
        migrations.CreateModel(
            name='MPHOTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('ctime', models.DateField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_album', to='pblog.MALBUM')),
            ],
            options={
                'verbose_name_plural': 'MPHOTOs',
                'verbose_name': 'MPHOTO',
            },
        ),
        migrations.AlterField(
            model_name='mcomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='pblog.MARTICLE'),
        ),
        migrations.AddField(
            model_name='mcomment',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_album', to='pblog.MALBUM'),
        ),
        migrations.AddField(
            model_name='mcomment',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_photo', to='pblog.MPHOTO'),
        ),
    ]
