# Generated by Django 2.1.7 on 2019-03-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0009_auto_20190329_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='malbum',
            name='description',
            field=models.CharField(blank=True, default='暂无描述', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mphoto',
            name='description',
            field=models.CharField(blank=True, default='暂无描述', max_length=500, null=True),
        ),
    ]
