# Generated by Django 2.1.7 on 2019-03-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0010_auto_20190329_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='malbum',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='mphoto',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
