# Generated by Django 2.1.7 on 2019-03-30 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pblog', '0012_auto_20190329_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPUBLISH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('ctime', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_article', to='pblog.MARTICLE')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_comment', to='pblog.MCOMMENT')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_photo', to='pblog.MPHOTO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MPUBLISH',
                'verbose_name_plural': 'MPUBLISHs',
            },
        ),
    ]
