# Generated by Django 2.1.7 on 2019-03-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0014_remove_mpublish_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpublish',
            name='user',
        ),
    ]
