# Generated by Django 2.1.7 on 2019-03-31 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0016_auto_20190331_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpublish',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pblog.MARTICLE'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pblog.MCOMMENT'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pblog.MPHOTO'),
        ),
    ]
