# Generated by Django 2.1.7 on 2019-03-31 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0017_auto_20190331_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpublish',
            name='types',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_article', to='pblog.MARTICLE'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_comment', to='pblog.MCOMMENT'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_photo', to='pblog.MPHOTO'),
        ),
    ]
