# Generated by Django 2.1.7 on 2019-03-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0018_auto_20190331_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpublish',
            name='article',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_article', to='pblog.MARTICLE'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_comment', to='pblog.MCOMMENT'),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mpublish',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_photo', to='pblog.MPHOTO'),
        ),
    ]
