# Generated by Django 2.1.7 on 2019-03-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0019_auto_20190331_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpublish',
            name='ctime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
