# Generated by Django 2.1.7 on 2019-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0020_auto_20190331_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpublish',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
