# Generated by Django 2.1.7 on 2019-03-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblog', '0022_auto_20190331_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malbum',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marticle',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mcomment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mphoto',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
